FROM localhost:5002/heedong/gpu-base:latest

WORKDIR /app

# Copy the requirements file first to leverage Docker layer caching
# COPY ./requirements/requirements_gputrainer.txt /app/requirements.txt

# Use the specific python interpreter to run pip to avoid version mismatches
# This ensures packages are installed for python3.11
# RUN python3.11 -m pip install --no-cache-dir -r /app/requirements.txt

# Copy the rest of the application code
COPY ./script/train_gpu.py /app/train_gpu.py
COPY ./app /app/app

# Set the command to run the training script directly
CMD ["python3.11", "/app/train_gpu.py"]