# mlops-fastapi-app/kubernetes/fastapi-api-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-internal-api-key-secret # FastAPI Deployment에서 참조할 이름
  namespace: default # FastAPI 앱이 배포될 네임스페이스
type: Opaque # 일반적인 키-값 데이터를 저장하는 Secret 타입
data:
  # API_KEY의 값은 Base64로 인코딩되어야 합니다.
  # 예를 들어, API 키를 "my-fastapi-internal-key"로 설정하고 싶다면,
  # 터미널에서 다음 명령어를 실행하여 Base64 값을 얻으세요:
  # echo -n "my-fastapi-internal-key" | base64
  # 그리고 그 결과값을 아래 API_KEY 필드에 붙여넣으세요.
  API_KEY: bXktZmFzdGFwaS1pbnRlcm5hbC1rZXk= # ⭐ 여기에 실제 API 키의 Base64 인코딩 값을 넣어주세요.