# minio-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001" # MinIO Console UI 포트
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret # 위에서 생성한 Secret의 이름
                  key: MINIO_ROOT_USER # Secret 내의 키 이름
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 9000 # MinIO API 포트
            - containerPort: 9001 # MinIO Console UI 포트
          volumeMounts:
            - name: minio-storage
              mountPath: /data # MinIO 데이터 경로
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc # Step 1에서 생성한 PVC와 연결
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: api # MLflow가 사용할 MinIO API 포트
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console # MinIO Console UI 포트
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort # 클러스터 내부에서만 접근 가능하도록 ClusterIP 타입 사용