# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque # 일반적인 키-값 쌍 Secret
data:
  MINIO_ROOT_USER: value # 예: echo -n 'minioadmin' | base64
  MINIO_ROOT_PASSWORD: pwd_value # 예: echo -n 'minioadminpassword' | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: value # 예: echo -n 'mlflow' | base64
  POSTGRES_PASSWORD: pwd_value # 예: echo -n 'mlflowpassword' | base64